# v3 syntax
version: '3'

# Named volumes
volumes:
  # MySQL Data
  hdcevents-mysql-data:
    driver: local

  # Redis Data
  hdcevents-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: hdcevents-mysql
    volumes:
      - hdcevents-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=hdcevents
      - MYSQL_DATABASE=hdcevents
      - MYSQL_USER=hdcevents
      - MYSQL_PASSWORD=hdcevents

  # Redis
  cache:
    image: redis:4.0
    container_name: hdcevents-redis
    command: --appendonly yes
    volumes:
      - hdcevents-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.3-nginx
    container_name: hdcevents-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
      - "8083:8083"
    links:
      - mysql
      - cache

  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hdcevents-phpmyadmin
    links:
      - mysql
    ports:
      - 8088:80
    environment:
      - PMA_ARBITRARY=1